# Override for deployment: use pre-built image from registry instead of building.
services:
  app:
    image: ${IMAGE_FULL_NAME}
    build: !reset null
    environment: 
      #override mysql url to use local installed mysql instance
      - SPRING_DATASOURCE_URL=jdbc:mysql://host.docker.internal:3306/instagramm
      - SERVER_BASE_URL=https://insta.api.usomi.de
      # use letsencrypt for ssl
      - VIRTUAL_HOST=insta.api.usomi.de,insta.api.local
      - VIRTUAL_PORT=8080
      - LETSENCRYPT_HOST=insta.api.usomi.de
    networks:
      - nginx_proxy_net
    extra_hosts:
      - "host.docker.internal:host-gateway" # for using local mysql

# this is external network for nginx proxy which handles SSL termination and routing to the app
networks:
  nginx_proxy_net:
    external: true